# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wedge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import slx_pb2 as slx__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wedge.proto',
  package='wedge',
  syntax='proto3',
  serialized_options=b'Z%github.com/Wappsto/wedge-api/go/wedge',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bwedge.proto\x12\x05wedge\x1a\tslx.proto\"$\n\x06\x44river\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"?\n\x05Model\x12\x1d\n\x06\x64river\x18\x01 \x01(\x0b\x32\r.wedge.Driver\x12\x17\n\x06\x64\x65vice\x18\x02 \x03(\x0b\x32\x07.Device\".\n\x0fSetModelRequest\x12\x1b\n\x05model\x18\x01 \x01(\x0b\x32\x0c.wedge.Model\"J\n\x10SetDeviceRequest\x12\x1d\n\x06\x64river\x18\x01 \x01(\x0b\x32\r.wedge.Driver\x12\x17\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\x07.Device\"Z\n\x0fSetValueRequest\x12\x1d\n\x06\x64river\x18\x01 \x01(\x0b\x32\r.wedge.Driver\x12\x11\n\tdevice_id\x18\x02 \x01(\r\x12\x15\n\x05value\x18\x03 \x01(\x0b\x32\x06.Value\"l\n\x0fSetStateRequest\x12\x1d\n\x06\x64river\x18\x01 \x01(\x0b\x32\r.wedge.Driver\x12\x11\n\tdevice_id\x18\x02 \x01(\r\x12\x10\n\x08value_id\x18\x03 \x01(\r\x12\x15\n\x05state\x18\x04 \x01(\x0b\x32\x06.State2\xc5\x01\n\x05Wedge\x12-\n\x08SetModel\x12\x16.wedge.SetModelRequest\x1a\x07.Replay\"\x00\x12/\n\tSetDevice\x12\x17.wedge.SetDeviceRequest\x1a\x07.Replay\"\x00\x12-\n\x08SetValue\x12\x16.wedge.SetValueRequest\x1a\x07.Replay\"\x00\x12-\n\x08SetState\x12\x16.wedge.SetStateRequest\x1a\x07.Replay\"\x00\x42\'Z%github.com/Wappsto/wedge-api/go/wedgeb\x06proto3'
  ,
  dependencies=[slx__pb2.DESCRIPTOR,])




_DRIVER = _descriptor.Descriptor(
  name='Driver',
  full_name='wedge.Driver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='wedge.Driver.host', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='wedge.Driver.port', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=69,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='wedge.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='wedge.Model.driver', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='wedge.Model.device', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=134,
)


_SETMODELREQUEST = _descriptor.Descriptor(
  name='SetModelRequest',
  full_name='wedge.SetModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='wedge.SetModelRequest.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=182,
)


_SETDEVICEREQUEST = _descriptor.Descriptor(
  name='SetDeviceRequest',
  full_name='wedge.SetDeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='wedge.SetDeviceRequest.driver', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='wedge.SetDeviceRequest.device', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=258,
)


_SETVALUEREQUEST = _descriptor.Descriptor(
  name='SetValueRequest',
  full_name='wedge.SetValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='wedge.SetValueRequest.driver', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='wedge.SetValueRequest.device_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='wedge.SetValueRequest.value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=350,
)


_SETSTATEREQUEST = _descriptor.Descriptor(
  name='SetStateRequest',
  full_name='wedge.SetStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='wedge.SetStateRequest.driver', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='wedge.SetStateRequest.device_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_id', full_name='wedge.SetStateRequest.value_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='wedge.SetStateRequest.state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=460,
)

_MODEL.fields_by_name['driver'].message_type = _DRIVER
_MODEL.fields_by_name['device'].message_type = slx__pb2._DEVICE
_SETMODELREQUEST.fields_by_name['model'].message_type = _MODEL
_SETDEVICEREQUEST.fields_by_name['driver'].message_type = _DRIVER
_SETDEVICEREQUEST.fields_by_name['device'].message_type = slx__pb2._DEVICE
_SETVALUEREQUEST.fields_by_name['driver'].message_type = _DRIVER
_SETVALUEREQUEST.fields_by_name['value'].message_type = slx__pb2._VALUE
_SETSTATEREQUEST.fields_by_name['driver'].message_type = _DRIVER
_SETSTATEREQUEST.fields_by_name['state'].message_type = slx__pb2._STATE
DESCRIPTOR.message_types_by_name['Driver'] = _DRIVER
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['SetModelRequest'] = _SETMODELREQUEST
DESCRIPTOR.message_types_by_name['SetDeviceRequest'] = _SETDEVICEREQUEST
DESCRIPTOR.message_types_by_name['SetValueRequest'] = _SETVALUEREQUEST
DESCRIPTOR.message_types_by_name['SetStateRequest'] = _SETSTATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Driver = _reflection.GeneratedProtocolMessageType('Driver', (_message.Message,), {
  'DESCRIPTOR' : _DRIVER,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.Driver)
  })
_sym_db.RegisterMessage(Driver)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.Model)
  })
_sym_db.RegisterMessage(Model)

SetModelRequest = _reflection.GeneratedProtocolMessageType('SetModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETMODELREQUEST,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.SetModelRequest)
  })
_sym_db.RegisterMessage(SetModelRequest)

SetDeviceRequest = _reflection.GeneratedProtocolMessageType('SetDeviceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETDEVICEREQUEST,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.SetDeviceRequest)
  })
_sym_db.RegisterMessage(SetDeviceRequest)

SetValueRequest = _reflection.GeneratedProtocolMessageType('SetValueRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETVALUEREQUEST,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.SetValueRequest)
  })
_sym_db.RegisterMessage(SetValueRequest)

SetStateRequest = _reflection.GeneratedProtocolMessageType('SetStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSTATEREQUEST,
  '__module__' : 'wedge_pb2'
  # @@protoc_insertion_point(class_scope:wedge.SetStateRequest)
  })
_sym_db.RegisterMessage(SetStateRequest)


DESCRIPTOR._options = None

_WEDGE = _descriptor.ServiceDescriptor(
  name='Wedge',
  full_name='wedge.Wedge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=463,
  serialized_end=660,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetModel',
    full_name='wedge.Wedge.SetModel',
    index=0,
    containing_service=None,
    input_type=_SETMODELREQUEST,
    output_type=slx__pb2._REPLAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetDevice',
    full_name='wedge.Wedge.SetDevice',
    index=1,
    containing_service=None,
    input_type=_SETDEVICEREQUEST,
    output_type=slx__pb2._REPLAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetValue',
    full_name='wedge.Wedge.SetValue',
    index=2,
    containing_service=None,
    input_type=_SETVALUEREQUEST,
    output_type=slx__pb2._REPLAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='wedge.Wedge.SetState',
    index=3,
    containing_service=None,
    input_type=_SETSTATEREQUEST,
    output_type=slx__pb2._REPLAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEDGE)

DESCRIPTOR.services_by_name['Wedge'] = _WEDGE

# @@protoc_insertion_point(module_scope)
