// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: wedge.proto

package wedge

import (
	context "context"
	slx "github.com/Wappsto/wedge-api/go/slx"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of slx.proto.

type NumberMapping = slx.NumberMapping

const NumberMapping_off = slx.NumberMapping_off
const NumberMapping_on = slx.NumberMapping_on

var NumberMapping_name = slx.NumberMapping_name
var NumberMapping_value = slx.NumberMapping_value

type Meta = slx.Meta
type State = slx.State
type Number = slx.Number
type String = slx.String
type Blob = slx.Blob
type Info = slx.Info
type Value = slx.Value
type Device = slx.Device
type Error = slx.Error
type Replay = slx.Replay

type Driver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Driver) Reset() {
	*x = Driver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Driver) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver *Driver       `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Device []*slx.Device `protobuf:"bytes,2,rep,name=device,proto3" json:"device,omitempty"`
}

func (x *Model) Reset() {
	*x = Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *Model) GetDevice() []*slx.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

// Create/Update all node data model
type SetModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *SetModelRequest) Reset() {
	*x = SetModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelRequest) ProtoMessage() {}

func (x *SetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelRequest.ProtoReflect.Descriptor instead.
func (*SetModelRequest) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{2}
}

func (x *SetModelRequest) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type SetDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver *Driver     `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Device *slx.Device `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *SetDeviceRequest) Reset() {
	*x = SetDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceRequest) ProtoMessage() {}

func (x *SetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{3}
}

func (x *SetDeviceRequest) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *SetDeviceRequest) GetDevice() *slx.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type SetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver   *Driver    `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	DeviceId uint32     `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Value    *slx.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{4}
}

func (x *SetValueRequest) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *SetValueRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SetValueRequest) GetValue() *slx.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver   *Driver    `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	DeviceId uint32     `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ValueId  uint32     `protobuf:"varint,3,opt,name=value_id,json=valueId,proto3" json:"value_id,omitempty"`
	State    *slx.State `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wedge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wedge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_wedge_proto_rawDescGZIP(), []int{5}
}

func (x *SetStateRequest) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *SetStateRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SetStateRequest) GetValueId() uint32 {
	if x != nil {
		return x.ValueId
	}
	return 0
}

func (x *SetStateRequest) GetState() *slx.State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_wedge_proto protoreflect.FileDescriptor

var file_wedge_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x77,
	0x65, 0x64, 0x67, 0x65, 0x1a, 0x09, 0x73, 0x6c, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x4f, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5a, 0x0a, 0x10, 0x53, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x73, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65,
	0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0f, 0x53,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32, 0xc5, 0x01, 0x0a, 0x05,
	0x57, 0x65, 0x64, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x79, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x17, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x79, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x57, 0x61, 0x70, 0x70, 0x73, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x64, 0x67, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x77, 0x65, 0x64, 0x67, 0x65, 0x50, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wedge_proto_rawDescOnce sync.Once
	file_wedge_proto_rawDescData = file_wedge_proto_rawDesc
)

func file_wedge_proto_rawDescGZIP() []byte {
	file_wedge_proto_rawDescOnce.Do(func() {
		file_wedge_proto_rawDescData = protoimpl.X.CompressGZIP(file_wedge_proto_rawDescData)
	})
	return file_wedge_proto_rawDescData
}

var file_wedge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wedge_proto_goTypes = []interface{}{
	(*Driver)(nil),           // 0: wedge.Driver
	(*Model)(nil),            // 1: wedge.Model
	(*SetModelRequest)(nil),  // 2: wedge.SetModelRequest
	(*SetDeviceRequest)(nil), // 3: wedge.SetDeviceRequest
	(*SetValueRequest)(nil),  // 4: wedge.SetValueRequest
	(*SetStateRequest)(nil),  // 5: wedge.SetStateRequest
	(*slx.Device)(nil),       // 6: Device
	(*slx.Value)(nil),        // 7: Value
	(*slx.State)(nil),        // 8: State
	(*slx.Replay)(nil),       // 9: Replay
}
var file_wedge_proto_depIdxs = []int32{
	0,  // 0: wedge.Model.driver:type_name -> wedge.Driver
	6,  // 1: wedge.Model.device:type_name -> Device
	1,  // 2: wedge.SetModelRequest.model:type_name -> wedge.Model
	0,  // 3: wedge.SetDeviceRequest.driver:type_name -> wedge.Driver
	6,  // 4: wedge.SetDeviceRequest.device:type_name -> Device
	0,  // 5: wedge.SetValueRequest.driver:type_name -> wedge.Driver
	7,  // 6: wedge.SetValueRequest.value:type_name -> Value
	0,  // 7: wedge.SetStateRequest.driver:type_name -> wedge.Driver
	8,  // 8: wedge.SetStateRequest.state:type_name -> State
	2,  // 9: wedge.Wedge.SetModel:input_type -> wedge.SetModelRequest
	3,  // 10: wedge.Wedge.SetDevice:input_type -> wedge.SetDeviceRequest
	4,  // 11: wedge.Wedge.SetValue:input_type -> wedge.SetValueRequest
	5,  // 12: wedge.Wedge.SetState:input_type -> wedge.SetStateRequest
	9,  // 13: wedge.Wedge.SetModel:output_type -> Replay
	9,  // 14: wedge.Wedge.SetDevice:output_type -> Replay
	9,  // 15: wedge.Wedge.SetValue:output_type -> Replay
	9,  // 16: wedge.Wedge.SetState:output_type -> Replay
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_wedge_proto_init() }
func file_wedge_proto_init() {
	if File_wedge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wedge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Driver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wedge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wedge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wedge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wedge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wedge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wedge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wedge_proto_goTypes,
		DependencyIndexes: file_wedge_proto_depIdxs,
		MessageInfos:      file_wedge_proto_msgTypes,
	}.Build()
	File_wedge_proto = out.File
	file_wedge_proto_rawDesc = nil
	file_wedge_proto_goTypes = nil
	file_wedge_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WedgeClient is the client API for Wedge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WedgeClient interface {
	SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*slx.Replay, error)
	SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*slx.Replay, error)
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*slx.Replay, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*slx.Replay, error)
}

type wedgeClient struct {
	cc grpc.ClientConnInterface
}

func NewWedgeClient(cc grpc.ClientConnInterface) WedgeClient {
	return &wedgeClient{cc}
}

func (c *wedgeClient) SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*slx.Replay, error) {
	out := new(slx.Replay)
	err := c.cc.Invoke(ctx, "/wedge.Wedge/SetModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wedgeClient) SetDevice(ctx context.Context, in *SetDeviceRequest, opts ...grpc.CallOption) (*slx.Replay, error) {
	out := new(slx.Replay)
	err := c.cc.Invoke(ctx, "/wedge.Wedge/SetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wedgeClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*slx.Replay, error) {
	out := new(slx.Replay)
	err := c.cc.Invoke(ctx, "/wedge.Wedge/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wedgeClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*slx.Replay, error) {
	out := new(slx.Replay)
	err := c.cc.Invoke(ctx, "/wedge.Wedge/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WedgeServer is the server API for Wedge service.
type WedgeServer interface {
	SetModel(context.Context, *SetModelRequest) (*slx.Replay, error)
	SetDevice(context.Context, *SetDeviceRequest) (*slx.Replay, error)
	SetValue(context.Context, *SetValueRequest) (*slx.Replay, error)
	SetState(context.Context, *SetStateRequest) (*slx.Replay, error)
}

// UnimplementedWedgeServer can be embedded to have forward compatible implementations.
type UnimplementedWedgeServer struct {
}

func (*UnimplementedWedgeServer) SetModel(context.Context, *SetModelRequest) (*slx.Replay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetModel not implemented")
}
func (*UnimplementedWedgeServer) SetDevice(context.Context, *SetDeviceRequest) (*slx.Replay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDevice not implemented")
}
func (*UnimplementedWedgeServer) SetValue(context.Context, *SetValueRequest) (*slx.Replay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (*UnimplementedWedgeServer) SetState(context.Context, *SetStateRequest) (*slx.Replay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}

func RegisterWedgeServer(s *grpc.Server, srv WedgeServer) {
	s.RegisterService(&_Wedge_serviceDesc, srv)
}

func _Wedge_SetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WedgeServer).SetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wedge.Wedge/SetModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WedgeServer).SetModel(ctx, req.(*SetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wedge_SetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WedgeServer).SetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wedge.Wedge/SetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WedgeServer).SetDevice(ctx, req.(*SetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wedge_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WedgeServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wedge.Wedge/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WedgeServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wedge_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WedgeServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wedge.Wedge/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WedgeServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wedge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wedge.Wedge",
	HandlerType: (*WedgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetModel",
			Handler:    _Wedge_SetModel_Handler,
		},
		{
			MethodName: "SetDevice",
			Handler:    _Wedge_SetDevice_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _Wedge_SetValue_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _Wedge_SetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wedge.proto",
}
